### ISSUE TITLE
KLC for Templates

### ISSUE THREAD

**Issue by heitorPB** [KiCad/kicad-templates#11]
There is no official guide on how to create a KiCad template. The only documentation about it is a small description about the needed files [here](http://docs.kicad-pcb.org/master/en/kicad.html#_creating_templates). 

Maybe adding a section in [KLC](http://kicad-pcb.org/libraries/klc/) for templates? That would be very useful for people creating new templates as well as for people using them. There is no convention for the names of libs/footprint/3D arquives. Each template has a different naming schema and that makes it confusing for new template development.

**Comment by antoniovazquezblanco** [comment]
Thanks for moving the issue!
