### ISSUE TITLE
The templates need to be converted over to use the new libs and the sym-lib-table

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-templates#4]
How do we best convert these templates over to use the new footprints?
Do we need to manually run the remap process on these? (should they first be made to use the new library to ensure that remapping works?)

**Comment by stambaughw** [comment]
I would remap them and let the rescuer create a rescue library with the
correct symbols recovered from the cache library (assuming it is
correct).  I suspect that given the age of some of the templates that
the original symbols have been modified or libraries have been renamed.
If you want to update them with the latest symbols, you could do that
manually after remapping.
